### ISSUE TITLE
Files directory creation is missing in model validation

### ISSUE THREAD

**Issue by KaixuanDai** [michielvandijk/mapspamc_mwi#1]
https://github.com/michielvandijk/mapspamc_mwi/blob/4f621e2d23b41be94462e66ff3776b240191ee9c/06_model_validation/01_alternative_model_setup.R#L32C1-L32C1
There seems to be a missing code in this place as 
```r
create_folders(param)
``` 
Otherwise, the following error appears in the next step. 
```
 GDX file 'E:/mapspamc_mwi-main/processed_data/intermediate_output/max_score_30sec_adm_level_1_solve_level_0/MWI/spamc_max_score_30sec_2010_MWI_MWI.gdx' not found
``` 
Because the files directory does not been created.

**Comment by michielvandijk** [comment]
I am not sure what you mean here. In principle there is no need to adjust 06/model_validation/01_alternative_model_setup.r as it takes all the parameters from the 'param' object by sourcing 01_model_setup/01_model_setup.r. When running model_validation/02_prepare_and_run_alternative_model.r is run, 01_alternative_model_setup.r is sourced and a new model and related folders and files are created on the fly. When I try the scripts it works. 

Where exactly in 02_prepare_and_run_alternative_model.r, you got this error. 

What is possible is that you perhaps changed parameters to 30sec before running that main 30sec model. In this case, the necessary input data was not created and errors might occur. When I have more time, I would like to add code to check the existence of the necessary input file that produce meaningful errors. This is not the case at the moment.

**Comment by KaixuanDai** [comment]
Thank you for your patient explanation.
I apologize for my previous misunderstanding that the `create_folders()` function would also create the `max_score_30sec_adm_level_{param$adm_level}_solve_level_{param$solve_level}` folder under the `processed_data\intermediate_output` path. 
It appears that this folder is created within the `03_model_preparation\01_model_preparation.R` script.

Thank you once again for your response.
